### ISSUE TITLE
[Bug] How to add mailto links for the Navbar link?

### ISSUE THREAD

**Issue by lll4770** [vuepress-theme-hope/vuepress-theme-hope#4049] opened 2024-04-07 08:28 UTC
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I add a emailto link in the narbar.ts file, something like the below
`text: "Contact Us",
    children: [
      {
        text: "Contact1",
        link: "https://www.google.co.jp/",
      },
      {
        text: "Email Support",
        link: "mailto:test123@gmail.com"
      }
    ],`
previously, it worked well; recently, I introduced "@vuepress/bundler-vite" in the config.ts(I don't know if it is the reason why the emailto link doesn't work), and I found the link "Email Support" pointing to a page "http://localhost:8080/mailto:test123@gmail.com.html";
(Just to clarify, that email isn't working now)

**Comment by Mister-Hope** [comment] 2024-04-07 08:30
Duplicate of https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/4044.

I need some help, so you can check that and help me.

**Closed by Mister-Hope** 2024-04-07 08:30 UTC
Labels: bug
