### ISSUE TITLE
A problem with Flowchart in vuepress-plugin-md-enhance 1.27.0

### ISSUE THREAD

**Issue by mlc-mlapis** [vuepress-theme-hope/vuepress-theme-hope#1586] opened 2022-03-17 13:21 UTC
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-plugin-md-enhance

### Version

v1

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [X] Linux

### Describe the bug

After upgrading to the 1.27.0 version (or any newest V1) of the `vuepress-plugin-md-enhance` package from the version 1.26.0, the following problem with the missing `MARKDOWN_ENHANCE_FLOWCHART` definition appears.

It looks like the problem is related to the changes in the files (packages/md-enhance/src/client/enhanceAppFile.ts and packages/md-enhance/src/node/index.ts) of the commit:

https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/a94a9d5a143cf9844136a2cd93c1864431302d3d

It seems that the `MARKDOWN_ENHANCE_FLOWCHART` is still used somewhere even when replaced in enhanceAppFile.ts and index.ts.

```
wait Extracting site metadata...
tip Apply local theme at /build/source/src/.vuepress/theme...
tip Apply theme local ...
root locates config is missing, and will return 'en-US' instead.
Note: This warning will be shown only once
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin element-tabs (i.e. "vuepress-plugin-element-tabs") ...
tip Apply plugin zooming (i.e. "vuepress-plugin-zooming") ...
tip Apply plugin md-enhance (i.e. "vuepress-plugin-md-enhance") ...
ℹ Compiling Client
ℹ Compiling Server
✔ Server: Compiled successfully in 1.02m
✔ Client: Compiled successfully in 1.02m
wait Rendering static HTML...
ReferenceError: MARKDOWN_ENHANCE_FLOWCHART is not defined
at enhanceApp (server-bundle.js:21839:3)
at server-bundle.js:22528:22
at Array.map (<anonymous>)
at _callee$ (server-bundle.js:22527:16)
at tryCatch (server-bundle.js:6291:40)
at Generator.invoke [as _invoke] (server-bundle.js:6522:22)
at Generator.next (server-bundle.js:6347:21)
at asyncGeneratorStep (server-bundle.js:13519:24)
at _next (server-bundle.js:13541:9)
at server-bundle.js:13548:7
at new Promise (<anonymous>)
at server-bundle.js:13537:12
at _createApp (server-bundle.js:22575:21)
at createApp (server-bundle.js:22486:21)
at module.exports.__webpack_exports__.default (server-bundle.js:22586:5)
at new Promise (<anonymous>)
at server-bundle.js:22585:10
at /usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:9439:15
at new Promise (<anonymous>)
at /usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:9401:14
at Object.renderToString (/usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:9577:9)
at Build.renderPage (/usr/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/build/index.js:160:34)
```

With the version 1.26.0 it works correctly:
```
wait Extracting site metadata...
tip Apply local theme at /build/source/src/.vuepress/theme...
tip Apply theme local ...
root locates config is missing, and will return 'en-US' instead.
Note: This warning will be shown only once
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin element-tabs (i.e. "vuepress-plugin-element-tabs") ...
tip Apply plugin zooming (i.e. "vuepress-plugin-zooming") ...
tip Apply plugin md-enhance (i.e. "vuepress-plugin-md-enhance") ...
ℹ Compiling Client
ℹ Compiling Server
✔ Server: Compiled successfully in 35.57s
✔ Client: Compiled successfully in 1.03m
wait Rendering static HTML...
success Generated static files in src/.vuepress/dist.
```

**Comment by Mister-Hope** [comment] 2022-03-18 04:29
Emm

![image](https://user-images.githubusercontent.com/33315834/158937606-d25eb519-a91d-4aa5-a2bb-0369ba130ec0.png)

Since I am not finding this variable, so a reproduction repo is needed.

Also, I may recommand you to switch to v2 versions.

**Comment by Mister-Hope** [comment] 2022-03-18 04:30
BTW, you may need to run `yarn upgrade` or `npm update` to make sure that you have a correct deps tree.

**Comment by mlc-mlapis** [comment] 2022-03-18 05:38
@Mister-Hope The funny thing is the fact that the problem appears only on a CI server when a new LXD build container is always created for each run (`npm i` is installing a completely new dependency tree). When doing the same locally it works fine. I don't understand how it is possible. Any idea?

**Comment by Mister-Hope** [comment] 2022-03-18 10:17
You should upload your lock file as well, to make sure you are using same version.

**Comment by Mister-Hope** [comment] 2022-03-18 10:21
I will close this one as the issue probably related to your env, and I am not getting enough infomation about it.

The suggestion is above.

**Closed by Mister-Hope** 2022-03-18 10:21 UTC
Labels: needs more info, v1

**Comment by mlc-mlapis** [comment] 2022-03-18 10:57
@Mister-Hope I am going to close this issue. It's really related only to our environment. Thank you for your cooperation indeed.
