### ISSUE TITLE
[Bug] Report an error in pageview.js with docs:dev

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2297] opened 2022-10-14 12:47 UTC
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

`docs:build` ran smoothly, and the building site was fine, but executing `docs:dev` reported an error.

```
20:43:35 [vite] Internal server error: Failed to resolve import "vuepress-plugin-comment2/lib/client/pageview.js" from "docs\.vuepress\.cache\deps\chunk-PKWOCWZ5.js?v=ea601e9d". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/blog/docs/.vuepress/.cache/deps/chunk-PKWOCWZ5.js?v=ea601e9d
  247|        updatePage(page ? Number(page) : 1);
  248|        if (SUPPORT_PAGEVIEW)
  249|          void import("vuepress-plugin-comment2/lib/client/pageview.js").then(({ updatePageview }) => {
     |                      ^
  250|            updatePageview();
  251|          });
```

**Comment by Mister-Hope** [comment] 2022-10-14 15:24
Or, another way, try to reproduce it on stackblitz, if the file does exisit and you can have everything work find on stackblitz, then I have nothing to do.

**Comment by rockbenben** [comment] 2022-10-14 17:23
> Or, another way, try to reproduce it on stackblitz, if the file does exisit and you can have everything work find on stackblitz, then I have nothing to do.

Yes, it exists and that's fine on StackBlitz. I will test it on StackBlitz first.

**Comment by Mister-Hope** [comment] 2022-10-15 12:04
Any details about issue or reasons?

**Comment by rockbenben** [comment] 2022-10-15 12:35
> Any details about issue or reasons?

I've cleared all the node_modules included in the cache, but still report errors.
```
20:29:34 [vite] Internal server error: Failed to resolve import "vuepress-plugin-comment2/lib/client/pageview.js" from "docs\.vuepress\.cache\deps\chunk-PKWOCWZ5.js?v=75d296f2". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/blog/docs/.vuepress/.cache/deps/chunk-PKWOCWZ5.js?v=75d296f2
  247|        updatePage(page ? Number(page) : 1);
  248|        if (SUPPORT_PAGEVIEW)
  249|          void import("vuepress-plugin-comment2/lib/client/pageview.js").then(({ updatePageview }) => {
     |                      ^
  250|            updatePageview();
  251|          });
at formatError (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
at TransformContext.error (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
at normalizeUrl (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
at async TransformContext.transform (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
at async Object.transform (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
at async loadAndTransform (file:///D:/blog/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)
```

**Comment by Mister-Hope** [comment] 2022-10-15 16:59
It might be something related to pnpm, I will relook into this later

**Comment by JQiue** [comment] 2022-10-17 09:20
我也有这个问题，从`beta.109`开始出现

当运行`vuepress run dev`时访问页面报错的信息
![image](https://user-images.githubusercontent.com/45145407/196139622-dbfcbd0b-5b75-4f52-955b-f35a06313939.png)
仔细检查了一下项目中，确实没有该目录和文件存在
![image](https://user-images.githubusercontent.com/45145407/196139910-4ce5dbee-b698-4e1a-9de7-65c4207441cc.png)
这个问题并不影响 build

**Comment by Mister-Hope** [comment] 2022-10-18 05:26
The problem is that vuepress-theme-hope file is incorrectly optimized, and `vuepress-plugin-comment2` is not a direct deps in project.

This is not happening in old version, I will try to figure this out.

**Comment by Mister-Hope** [comment] 2022-10-22 03:50
I am not sure if beta.111 fix this issue, can you please provide some feedback?

**Comment by mrwangjinqiu** [comment] 2022-10-22 03:51
我马上测试

**Comment by JQiue** [comment] 2022-10-22 04:03
仍然不能解决，这是访问后得到的错误信息

```
vuepress-plugin-pwa2:  ⚠ The plugin will register service worker to handle assets, so we recommend you to set "shouldPrefetch: false" in VuePress config file.
✔ Initializing and preparing data - done in 2.29s

  vite v3.0.9 dev server running at:

  ➜  Local:   http://localhost:8080/    
  ➜  Network: http://192.168.2.100:8080/
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
Failed to resolve import "vuepress-plugin-comment2/lib/client/pageview.js" from "docs\.vuepress\.cache\deps\chunk-D4PD5S7K.js?v=be95f6f4". Does the file exist?
Failed to resolve import "vuepress-plugin-comment2/lib/client/pageview.js" from "docs\.vuepress\.cache\deps\chunk-D4PD5S7K.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
11:59:14 [vite] Internal server error: Failed to resolve import "@vuepress/plugin-theme-data/client" from "docs\.vuepress\.cache\deps\chunk-OD5U7U6J.js?v=be95f6f4". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/JQiue/Desktop/jqiue-notes/docs/.vuepress/.cache/deps/chunk-OD5U7U6J.js?v=be95f6f4
  30 |  
  31 |  // node_modules/.pnpm/vuepress-theme-hope@2.0.0-beta.111/node_modules/vuepress-theme-hope/lib/client/composables/themeData.js
  32 |  import { useThemeData as _useThemeData, useThemeLocaleData as _useThemeLocaleData } from "@vuepress/plugin-theme-data/client";
     |                                                                                            ^
  33 |  var useThemeData = () => _useThemeData();
  34 |  var useThemeLocaleData = () => _useThemeLocaleData();
      at formatError (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
      at TransformContext.error (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
      at normalizeUrl (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
      at async TransformContext.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
      at async Object.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
      at async loadAndTransform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)
11:59:14 [vite] Internal server error: Failed to resolve import "@vuepress/plugin-external-link-icon/client" from "docs\.vuepress\.cache\deps\chunk-DUMQTKXZ.js?v=be95f6f4". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/JQiue/Desktop/jqiue-notes/docs/.vuepress/.cache/deps/chunk-DUMQTKXZ.js?v=be95f6f4
  22 |  
  23 |  // node_modules/.pnpm/vuepress-theme-hope@2.0.0-beta.111/node_modules/vuepress-theme-hope/lib/client/components/AutoLink.js
  24 |  import { ExternalLinkIcon } from "@vuepress/plugin-external-link-icon/client";
     |                                    ^
  25 |  var AutoLink_default = defineComponent({
  26 |    name: "AutoLink",
      at formatError (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
      at TransformContext.error (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
      at normalizeUrl (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
      at async TransformContext.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
      at async Object.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
      at async loadAndTransform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)
11:59:14 [vite] Internal server error: Failed to resolve import "vuepress-plugin-comment2/lib/client/pageview.js" from "docs\.vuepress\.cache\deps\chunk-D4PD5S7K.js?v=be95f6f4". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/JQiue/Desktop/jqiue-notes/docs/.vuepress/.cache/deps/chunk-D4PD5S7K.js?v=be95f6f4
  254|        updatePage(page ? Number(page) : 1);
  255|        if (SUPPORT_PAGEVIEW)
  256|          void import("vuepress-plugin-comment2/lib/client/pageview.js").then(({ updatePageview }) => {
     |                      ^
  257|            updatePageview();
  258|          });
      at formatError (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
      at TransformContext.error (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
      at normalizeUrl (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
      at async TransformContext.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
      at async Object.transform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
      at async loadAndTransform (file:///C:/Users/JQiue/Desktop/jqiue-notes/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:29)

```

**Comment by rockbenben** [comment] 2022-10-22 04:09
I have a similar error report as JQiue's.

**Comment by Mister-Hope** [comment] 2022-10-22 04:23
是不是忘记升级vp到beta52

**Comment by rockbenben** [comment] 2022-10-22 04:59
升级过的
```
  "dependencies": {
    "@vuepress/client": "2.0.0-beta.52",
    "@vuepress/plugin-docsearch": "2.0.0-beta.52",
    "@vuepress/plugin-google-analytics": "2.0.0-beta.52",
    "@vuepress/plugin-search": "2.0.0-beta.52",
    "@vuepress/utils": "2.0.0-beta.52",
    "pnpm": "^7.13.6",
    "vue": "^3.2.41",
    "vuepress": "2.0.0-beta.52",
    "vuepress-theme-hope": "2.0.0-beta.111"
  }
```

**Comment by JQiue** [comment] 2022-10-22 05:07
我补充一个刚开始开始的叙述错误，vscode 把我的.cache文件给排除了，这是我在目录中没有看到它的原因

**Comment by Mister-Hope** [comment] 2022-10-22 12:06
I tried to fix this in beta.113. but I am not sure.

**Comment by Mister-Hope** [comment] 2022-10-22 12:16
I am not be able to reproduce this issue with beta.133 with my blog. so if you guys are still contering problems, a mininal reproduction genreated from template is required.

 ( I am really BUSY these days so I do need a mininal reproduction repo to save my time.🥺)

**Comment by JQiue** [comment] 2022-10-22 12:42
感谢你所做的工作，beta.113 仍然不能解决问题，有时间我将尝试使用最小示例进行重现

**Comment by rockbenben** [comment] 2022-10-22 13:57
This works perfectly in my case with beta.113. Is it because of dependencies or other? @JQiue 

```json
  "dependencies": {
    "@vuepress/client": "2.0.0-beta.52",
    "@vuepress/plugin-docsearch": "2.0.0-beta.52",
    "@vuepress/plugin-google-analytics": "2.0.0-beta.52",
    "@vuepress/plugin-search": "2.0.0-beta.52",
    "@vuepress/utils": "2.0.0-beta.52",
    "pnpm": "^7.14.0",
    "vue": "^3.2.41",
    "vuepress": "2.0.0-beta.52",
    "vuepress-theme-hope": "2.0.0-beta.113"
  }
```

**Comment by JQiue** [comment] 2022-10-23 04:09
OK，经过反复调试，这个问题差不多已经得到解决了，必须保证`vuepress`版本号为`2.0.0-beta.52`，不能有`^`前缀，否则它将安装为`pre-1`版本

**Comment by JQiue** [comment] 2022-10-23 04:15
我还发现一个关于 PageView 的问题，我会作为另一个 issue 叙述

**Comment by Mister-Hope** [comment] 2022-10-23 04:15
OK, I will close this one.

**Closed by Mister-Hope** 2022-10-23 04:15 UTC
Labels: bug
